image: cypress/browsers:node18.12.0-chrome107

stages:
  - test

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  paths:
    - node_modules/
    - cache/Cypress

cypress_scheduled_test:
  stage: test
  script:
    - npm ci
    - CYPRESS_baseUrl=$E2E_BASE_URL CYPRESS_loginType=$CYPRESS_LOGIN_TYPE npx cypress run --spec "cypress/e2e/01-v2_regression/01_authLogin.cy.js"

    - CYPRESS_baseUrl=$E2E_BASE_URL CYPRESS_loginType=$CYPRESS_LOGIN_TYPE npx cypress run --spec "cypress/e2e/01-v2_regression/01_authRegister.cy.js"

    - CYPRESS_baseUrl=$E2E_BASE_URL CYPRESS_loginType=$CYPRESS_LOGIN_TYPE npx cypress run --spec "cypress/e2e/01-v2_regression/01_authOnboarding.cy.js"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main")'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $RUN_CI_SUITE == "auth"'

cypress_conversation_runner_checker:
  stage: test
  script:
    - npm ci
    - CYPRESS_baseUrl=$E2E_BASE_URL CYPRESS_loginType=$CYPRESS_LOGIN_TYPE npx cypress run --spec "cypress/e2e/01-v2_regression/02_conversation_runnerChecker.cy.js"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main")'
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $RUN_CI_SUITE == "conversation"'
