function generateRandomQuote() {
  const quotes = [
    "Success is not final; failure is not fatal: It is the courage to continue that counts.",
    "Believe you can and you're halfway there.",
    "Act as if what you do makes a difference. It does.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don't be afraid to give up the good to go for the great.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is not in what you have, but who you are.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "The best way to predict the future is to create it.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Opportunities don't happen. You create them.",
    "Success is how high you bounce when you hit bottom.",
    "Your time is limited, so don't waste it living someone else's life.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "Do what you can, with what you have, where you are.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Dream big and dare to fail.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Don't watch the clock; do what it does. Keep going.",
    "The journey of a thousand miles begins with one step.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Difficulties in life are intended to make us better, not bitter.",
    "The only person you are destined to become is the person you decide to be.",
    "Don’t count the days, make the days count.",
    "Every strike brings me closer to the next home run.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "You define your own life. Don’t let other people write your script.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "The best revenge is massive success.",
    "Do not let what you cannot do interfere with what you can do.",
    "It is never too late to be what you might have been.",
    "Turn your wounds into wisdom.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "We may encounter many defeats but we must not be defeated.",
    "Your life only gets better when you get better.",
    "Failure is another stepping stone to greatness.",
    "The man who has confidence in himself gains the confidence of others.",
    "Happiness is not something ready made. It comes from your own actions.",
    "If you want to lift yourself up, lift up someone else.",
    "No one can make you feel inferior without your consent.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "You miss 100% of the shots you don’t take.",
    "Don’t wait. The time will never be just right.",
    "Whether you think you can or you think you can’t, you’re right.",
    "To be a champion, you have to believe in yourself when no one else will.",
    "Always do your best. What you plant now, you will harvest later.",
    "Go confidently in the direction of your dreams. Live the life you have imagined.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is stumbling from failure to failure with no loss of enthusiasm",
    "The difference between ordinary and extraordinary is that little extra",
    "If you’re going through hell, keep going",
    "Perseverance is not a long race; it is many short races one after another",
    "It’s not about how hard you can hit; it’s about how hard you can get hit and keep moving forward",
    "Start where you are. Use what you have. Do what you can",
    "Don’t wait for opportunity. Create it",
    "Do not be embarrassed by your failures; learn from them and start again",
    "You are never too old to set another goal or to dream a new dream",
    "If you want something you've never had, you must be willing to do something you've never done",
    "Success is getting what you want. Happiness is wanting what you get",
    "Don’t let yesterday take up too much of today",
    "Push yourself, because no one else is going to do it for you",
    "Success doesn’t just find you. You have to go out and get it",
    "Dream it. Wish it. Do it",
    "Your limitation—it’s only your imagination",
    "Great things never come from comfort zones",
    "Dream bigger. Do bigger",
    "It always seems impossible until it’s done",
    "Dreams don’t work unless you do",
    "Go the extra mile. It’s never crowded",
    "Don’t stop when you’re tired. Stop when you’re done",
    "You don’t have to be great to start, but you have to start to be great",
    "Wake up with determination. Go to bed with satisfaction",
    "Do something today that your future self will thank you for",
    "Little things make big days",
    "It’s going to be hard, but hard does not mean impossible",
    "Don’t wait for an opportunity. Create it",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths",
    "The key to success is to focus on goals, not obstacles",
    "Dream it. Believe it. Build it",
    "Be a warrior, not a worrier",
    "It’s never too late to be what you might have been",
    "If you’re not willing to risk the usual, you’ll have to settle for the ordinary",
    "I have not failed. I’ve just found 10,000 ways that won’t work",
    "Failure will never overtake me if my determination to succeed is strong enough",
    "The only place where success comes before work is in the dictionary",
    "The way to get started is to quit talking and begin doing",
    "Don't be afraid to give up the good to go for the great",
    "I find that the harder I work, the more luck I seem to have",
    "Opportunities don't happen. You create them",
    "Don't be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you",
    "I have learned over the years that when one’s mind is made up, this diminishes fear",
    "You may have to fight a battle more than once to win it",
    "Keep going. Everything you need will come to you at the perfect time",
    "A river cuts through rock not because of its power but because of its persistence",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
    "The ones who are crazy enough to think they can change the world are the ones who do",
    "No matter how hard the past, you can always begin again",
    "Your life only gets better when you get better",
    "Turn your wounds into wisdom",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well",
    "To succeed in life, you need two things: ignorance and confidence",
    "It is our choices that show what we truly are, far more than our abilities",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit",
    "If you cannot do great things, do small things in a great way",
    "Be not afraid of going slowly, be afraid only of standing still",
    "A winner is a dreamer who never gives up",
    "You miss 100% of the shots you don’t take",
    "Do something today that your future self will thank you for",
    "Success is not just about making money; it’s about making a difference in people’s lives",
    "Believe in your dreams, no matter how impossible they may seem",
    "Focus on the step in front of you, not the whole staircase",
    "Success is best when it’s shared",
    "Effort only fully releases its reward after a person refuses to quit",
    "Discipline is the bridge between goals and accomplishment",
    "Be brave. Take risks. Nothing can substitute experience",
    "The future belongs to those who believe in the beauty of their dreams",
    "The greatest glory in living lies not in never falling, but in rising every time we fall",
    "The power of imagination makes us infinite",
    "A goal without a plan is just a wish",
    "It always seems impossible until it’s done",
    "Dream as if you’ll live forever. Live as if you’ll die today",
    "Life is short. Live it. Fear is natural. Face it. Memory is powerful. Use it",
    "It’s not whether you get knocked down; it’s whether you get up",
    "Good things come to people who wait, but better things come to those who go out and get them",
    "Success is walking from failure to failure with no loss of enthusiasm",
    "The harder you work, the luckier you get",
    "Success is the sum of small efforts, repeated day in and day out",
    "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t",
    "Work hard in silence; let your success be your noise",
    "If you want to achieve greatness stop asking for permission",
    "Sometimes you win, sometimes you learn",
    "You can’t have a million-dollar dream with a minimum-wage work ethic",
    "The distance between dreams and reality is called action",
    "A little progress each day adds up to big results",
    "Strive not to be a success, but rather to be of value",
    "The pain you feel today will be the strength you feel tomorrow",
    "Don’t decrease the goal. Increase the effort",
    "Everything you’ve ever wanted is on the other side of fear",
    "Success is not just a goal; it’s a byproduct of the journey",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone",
    "Whatever you are, be a good one",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful",
    "There are no limits to what you can accomplish, except the limits you place on your own thinking",
    "Success isn’t about being the best; it’s about always getting better",
    "It is not in the stars to hold our destiny but in ourselves",
    "You are not defined by your past; you are prepared by your past",
    "Do one thing every day that scares you",
    "Act as if what you do makes a difference. It does",
    "A smooth sea never made a skilled sailor",
    "You don’t have to be great to start, but you have to start to be great",
    "The only way to do great work is to love what you do",
    "Be yourself; everyone else is already taken",
    "The road to success is dotted with many tempting parking spaces",
    "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change",
    "Don’t watch the clock; do what it does. Keep going",
    "Life isn’t about waiting for the storm to pass; it’s about learning to dance in the rain",
    "Success is liking yourself, liking what you do, and liking how you do it",
    "Focus on where you want to go, not on what you fear",
    "Start where you are. Use what you have. Do what you can",
    "Success isn’t about how much money you make; it’s about the difference you make in people’s lives",
    "The only person you should try to be better than is the person you were yesterday",
    "Believe you can and you’re halfway there",
    "The secret of getting ahead is getting started",
    "The best way to predict the future is to invent it",
    "Success is not in what you have, but who you are",
    "Don’t let small minds convince you that your dreams are too big",
    "Your life does not get better by chance, it gets better by change",
    "Keep your eyes on the stars, and your feet on the ground",
    "Success usually comes to those who are too busy to be looking for it",
    "Do what you can, with what you have, where you are",
    "It’s not about being the best. It’s about being better than you were yesterday",
    "The journey of a thousand miles begins with one step",
    "The way to get started is to quit talking and begin doing",
    "If you want to make your dreams come true, the first thing you have to do is wake up",
    "It takes courage to grow up and become who you really are",
    "What you get by achieving your goals is not as important as what you become by achieving your goals",
    "The only place where success comes before work is in the dictionary",
    "Opportunities are usually disguised as hard work, so most people don’t recognize them",
    "The only limit to our realization of tomorrow is our doubts of today",
    "Do not let what you cannot do interfere with what you can do",
    "Small deeds done are better than great deeds planned",
    "Success is not just about earning money; it’s about making an impact",
    "One day or day one. You decide",
    "Do not wait; the time will never be ‘just right’",
    "You define your own life. Don’t let other people write your script",
    "Hustle beats talent when talent doesn’t hustle",
    "Don’t be afraid to start over. It’s a chance to build something better this time",
    "The best revenge is massive success",
    "Success is not final, failure is not fatal: it is the courage to continue that counts",
    "Don't let anyone ever dull your sparkle",
    "What you do today can improve all your tomorrows",
    "It’s not the years in your life that count; it’s the life in your years",
    "Don't limit your challenges. Challenge your limits",
    "Success is what happens after you have survived all of your mistakes",
    "The only difference between ordinary and extraordinary is that little extra",
    "Strength doesn’t come from what you can do; it comes from overcoming the things you once thought you couldn’t",
    "The greater the obstacle, the more glory in overcoming it",
    "You miss 100% of the shots you don’t take",
    "Let your dreams be bigger than your fears and your actions louder than your words",
    "Success is the best revenge",
    "Success is not how high you have climbed, but how you make a positive difference to the world",
    "Dream big and dare to fail",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "The best way to predict your future is to create it. – Peter Drucker",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. – Maya Angelou",
    "Every moment is a fresh beginning. – T.S. Eliot",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "Doubt kills more dreams than failure ever will. – Suzy Kassem",
    "Dream big and dare to fail. – Norman Vaughan",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "You can, you should, and if you’re brave enough to start, you will. – Stephen King",
    "If you can dream it, you can achieve it. – Zig Ziglar",
    "Life isn’t about waiting for the storm to pass but learning to dance in the rain. – Vivian Greene",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
    "Believe you can and you’re halfway there. – Theodore Roosevelt",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination. – Jimmy Dean",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Life is either a daring adventure or nothing at all. – Helen Keller",
    "Act as if what you do makes a difference. It does. – William James",
    "Perfection is not attainable, but if we chase perfection we can catch excellence. – Vince Lombardi",
    "Turn your wounds into wisdom. – Oprah Winfrey",
    "It is never too late to be what you might have been. – George Eliot",
    "Great things are done by a series of small things brought together. – Vincent Van Gogh",
    "You are the sum of the choices you make. – Wayne Dyer",
    "Your life does not get better by chance, it gets better by change. – Jim Rohn",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "In three words I can sum up everything I’ve learned about life: it goes on. – Robert Frost",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
    "When you have a dream, you've got to grab it and never let go",
    "Opportunities don't happen, you create them",
    "The only limit to our realization of tomorrow is our doubts of today",
    "Keep your face always toward the sunshine, and shadows will fall behind you",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful",
    "Happiness is not by chance, but by choice",
    "If you’re going through hell, keep going",
    "We may encounter many defeats, but we must not be defeated",
    "Success is not in what you have, but who you are",
    "Life shrinks or expands in proportion to one’s courage",
    "In the end, we only regret the chances we didn’t take",
    "Start where you are, use what you have, do what you can",
    "Sometimes the bravest and most important thing you can do is just show up",
    "Your big opportunity may be right where you are now",
    "Courage doesn’t always roar; sometimes courage is the quiet voice at the end of the day saying 'I will try again tomorrow'",
    "The purpose of life is a life of purpose",
    "To live is the rarest thing in the world; most people just exist",
    "It’s not what happens to you, but how you react to it that matters",
    "We must embrace pain and burn it as fuel for our journey",
    "Nothing is impossible, the word itself says 'I’m possible'",
    "Don't count the days, make the days count",
    "Success is not how high you have climbed, but how you make a positive difference to the world",
    "A goal without a plan is just a wish",
    "The mind is everything; what you think, you become",
    "Don’t wait for the perfect moment; take the moment and make it perfect",
    "Live each day as if your life had just begun",
    "The harder you work for something, the greater you’ll feel when you achieve it",
    "Be so good they can’t ignore you",
    "Strive not to be a success, but rather to be of value",
    "Believe in yourself and all that you are; know that there is something inside you that is greater than any obstacle",
  ];
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}

function randomAsk() {
  const Ask = [
    // Pertanyaan existing (dipertahankan)
    "Kapan barang saya akan dikirim?",
    "Berapa lama estimasi waktu pengiriman?",
    "Apakah saya bisa melacak pengiriman barang saya?",
    "Apakah bisa memilih jasa ekspedisi tertentu?",
    "Apakah pengiriman tersedia ke luar kota/luar negeri?",
    "Mengapa barang saya belum sampai padahal statusnya sudah terkirim?",
    "Bagaimana jika barang saya hilang dalam proses pengiriman?",
    "Apa yang harus saya lakukan jika saya tidak menerima barang saya?",
    "Apakah ada penggantian jika barang hilang atau rusak selama pengiriman?",
    "Siapa yang bertanggung jawab atas kehilangan barang dalam pengiriman?",
    "Berapa biaya pengiriman ke alamat saya?",
    "Apakah biaya pengiriman dihitung per berat atau per ukuran?",
    "Apakah ada promo gratis ongkir?",
    "Apakah ongkir bisa dibayar di tempat (COD)?",
    "Apakah biaya pengiriman akan berubah jika ada pengiriman ulang?",
    "Barangku dikirimnya kapan ya?",
    "Biasanya butuh berapa lama sih buat sampai?",
    "When will my package be shipped?",
    "How long does the delivery usually take?",
    "Where can I track my shipment?",
    "Can I choose the delivery service myself?",
    "Do you ship to other cities or countries?",
    "My package says delivered but I haven’t got it. What’s up?",
    "What if my package gets lost on the way?",
    "I haven’t received my order yet, what should I do?",
    "Will I get a refund if my stuff is broken during delivery?",
    "Who’s responsible if my package goes missing?",
    "How much is the shipping fee to my address?",
    "Is the shipping cost based on weight or size?",
    "Do you guys have free shipping promos?",
    "Can I pay the shipping fee when the package arrives (COD)?",
    "If I need the item reshipped, do I have to pay more?",
    "Bisa lacak kiriman aku di mana?",
    "Boleh nggak pilih ekspedisi sendiri?",
    "Ngirim ke luar kota atau luar negeri bisa nggak?",
    "Statusnya udah terkirim tapi barangnya belum nyampe, kenapa ya?",
    "Barangku hilang di jalan, gimana dong?",
    "Aku belum terima barangnya, harus ngapain?",
    "Kalau barangnya rusak pas dikirim, bisa diganti nggak?",
    "Kalau barang hilang, siapa yang tanggung jawab?",
    "Ongkir ke alamatku berapa sih?",
    "Ongkirnya dihitung dari berat atau ukuran barang ya?",
    "Ada promo gratis ongkir nggak?",
    "Ongkir bisa dibayar pas barang sampai nggak (COD)?",
    "Kalau harus kirim ulang, ongkirnya nambah nggak?",
    "Bagaimana cara mengetahui status pengiriman barang saya?",
    "Apakah saya akan menerima nomor resi setelah pengiriman?",
    "Bagaimana jika saya salah memasukkan alamat pengiriman?",
    "Apakah saya bisa mengubah alamat setelah barang dikirim?",
    "Apakah ada biaya tambahan untuk pengiriman ulang?",
    "Bagaimana prosedur klaim barang hilang atau rusak?",
    "Apakah pengiriman dilakukan setiap hari, termasuk akhir pekan?",
    "Apakah saya bisa memilih waktu pengiriman tertentu?",
    "Bagaimana jika kurir datang tapi saya tidak di rumah?",
    "Apakah barang bisa diambil sendiri jika gagal dikirim?",
    "Apa saja metode pembayaran untuk biaya pengiriman?",
    "Apakah saya bisa meminta pengiriman lebih cepat (ekspres)?",
    "Apakah tersedia pengiriman dalam hari yang sama (same day)?",
    "Apakah ada batasan jenis barang yang bisa dikirim?",
    "Bagaimana jika saya menerima barang yang tidak sesuai?",
    "Gimana sih cara cek status pengiriman aku?",
    "Dapat nomor resi nggak sih abis barang dikirim?",
    "Gimana kalau aku salah masukin alamat?",
    "Alamatnya bisa diganti nggak kalau barang udah dikirim?",
    "Kalau minta kirim ulang, ada biaya tambahan lagi nggak?",
    "Kalau barang rusak/hilang, cara klaimnya gimana ya?",
    "Pengiriman jalan terus nggak pas weekend?",
    "Bisa request dikirim jam tertentu nggak?",
    "Kalau kurir datang tapi aku lagi nggak di rumah, gimana?",
    "Bisa ambil sendiri barangnya kalau gagal kirim?",
    "Bayar ongkirnya bisa lewat apa aja?",
    "Bisa minta pengiriman cepat (ekspres) nggak?",
    "Ada layanan kirim di hari yang sama (same day) nggak?",
    "Barang apa aja sih yang nggak bisa dikirim?",
    "Kalau barang yang dateng nggak sesuai, harus ngapain?",

    // Tambahan pertanyaan natural dalam bahasa Indonesia formal
    "Apakah pengiriman akan terpengaruh jika terjadi banjir atau bencana alam?",
    "Bagaimana prosedur pengembalian barang jika tidak sesuai pesanan?",
    "Apakah ada jaminan uang kembali jika barang tidak sampai dalam 7 hari?",
    "Berapa lama waktu proses packing sebelum barang dikirim?",
    "Apakah bisa mengirim barang dengan nilai tinggi? Apakah ada asuransi?",
    "Bagaimana cara memastikan paket aman saat pengiriman jarak jauh?",
    "Apakah tersedia opsi pengiriman ramah lingkungan?",
    "Bagaimana jika penerima tidak ada di alamat tujuan saat pengiriman?",
    "Apakah ada batasan berat maksimal untuk pengiriman reguler?",
    "Bisakah saya menitipkan pesanan untuk diambil oleh orang lain?",
    "Apakah pengiriman bisa dilakukan ke alamat kantor atau hanya rumah?",
    "Bagaimana cara mengkonfirmasi bahwa barang sudah diterima dengan baik?",
    "Apakah ada diskon pengiriman untuk pelanggan setia?",
    "Berapa lama klaim kerusakan barang akan diproses?",
    "Apakah bisa mengganti jasa ekspedisi setelah pesanan dibuat?",

    // Tambahan pertanyaan natural dalam bahasa Inggris
    "Does the delivery fee include insurance?",
    "Can I get a delivery estimate before placing my order?",
    "What happens if my package is damaged during transit?",
    "Do you deliver on public holidays?",
    "How can I provide special delivery instructions?",
    "Is there a weight limit for international shipping?",
    "Can I ship to a PO Box address?",
    "What packaging materials do you use for fragile items?",
    "How do I know if my area is covered for delivery?",
    "Can I combine multiple orders to save on shipping?",
    "What's the difference between standard and express shipping?",
    "Do I need to be present to sign for the package?",
    "How far in advance should I place an order for holiday delivery?",
    "Can I request the courier to call me before delivery?",
    "What happens if I enter the wrong phone number for delivery?",

    // Tambahan pertanyaan natural dalam slang/sehari-hari
    "Gue urgent banget nih, bisa gak dikirim hari ini juga?",
    "Kirimanku kok stuck di gudang ya? Udah 2 hari gak gerak-gerak.",
    "Males banget harus ke kantor pos, bisa gak diantar langsung ke rumah?",
    "Bungkusannya rapih gak? Takutnya pecah nih isinya.",
    "Kemaren kan hujan deras, aman gak ya kiriman gue?",
    "Bisa gak sih kasih kurir yang cantik? Biar happy hehe",
    "Ongkirnya kok mahal banget sih? Ada yang lebih murah gak?",
    "Gue kemaren pesen jam 10, kok baru dikirim sore ini?",
    "Barangnya udah sampe tapi gue lagi di luar kota, gimana dong?",
    "Bisa gak kirimnya pakai GoSend? Lebih cepet tuh.",
    "Gue mau kirim surprise buat pacar, bisa bungkus kado gak?",
    "Kalau barangnya nggak muat di motor, pakai apa ya?",
    "Resinya kok gak bisa dilacak ya? Error mulu.",
    "Bisa gak anter malam hari? Soalnya gue pulang kerja jam 8.",
    "Gue mau komplain nih, kurirnya nggak sopan banget!",

    // Tambahan percakapan natural (melanjutkan yang existing)
    "Eh bro, lo liat gak sih story si Rani tadi malem?",
    "Gila sih, vibes-nya kayak lagi di Bali padahal cuma di rooftop mall",
    "Wkwkwk iya gue liat!",
    "Anak itu emang aesthetic banget dah hidupnya, feed IG-nya udah kayak katalog Pinterest.",
    "alah bacot",
    "Btw, lo pesen baju baru dari mana? Kirimannya cepet banget.",
    "Dari Shopee lah, ongkirnya gratis lagi. Gue kemaren order Senin, Rabu udah sampe.",
    "Wah asik tuh! Gue kemaren order di Tokped kok lama banget, baru dateng seminggu.",
    "Mungkin karena alamat lo di pelosok kali ya? Hahaha.",
    "Iya nih, di kampung emang susah. Kadang kurirnya juga males ngantar ke sini.",
    "Pernah gue order barang elektronik, pas dateng malah pecah. Ribet banget mau komplain.",
    "Hadeuh... sama gue juga pernah. Akhirnya gue kapok deh order barang pecah belah online.",
    "Lebih baik beli langsung di toko aja kali ya, biar gak pusing.",
    "Iya nih, tapi males juga harus keluar rumah. Apalagi sekarang lagi panas-panasnya.",
    "Ya udah deh, gue ikutan aja belanja online. Tapi harus baca review dulu biar gak ketipu.",
  ];
  const randomIndex = Math.floor(Math.random() * Ask.length);
  return Ask[randomIndex];
}

function randomAsk2() {
  const ask2 = [
    // Alternatif Pertanyaan Formal (Indonesia)
    "Kapan paket saya akan diproses dan dikirim?",
    "Berapa estimasi waktu sampai ke alamat tujuan?",
    "Apakah saya bisa memantau status pengiriman melalui resi?",
    "Bisakah saya memilih jasa kurir yang saya inginkan?",
    "Apakah layanan pengiriman tersedia hingga ke luar negeri?",
    "Mengapa status pengiriman sudah selesai, tapi barang belum saya terima?",
    "Apa yang harus saya lakukan jika paket hilang di perjalanan?",
    "Apakah ada asuransi jika barang rusak dalam pengiriman?",
    "Siapa pihak yang bertanggung jawab bila terjadi kehilangan barang?",
    "Bagaimana cara klaim jika barang saya rusak?",
    // 🔹 Alternatif Santai / Sehari-hari (Indonesia)
    "Paket gue dikirim kapan sih?",
    "Biasanya nyampe berapa lama ya?",
    "Resi bisa dicek di mana ya?",
    "Boleh nggak milih kurir sendiri?",
    "Ngirim ke luar kota bisa kan?",
    "Kok status udah delivered tapi gue belum dapet barang?",
    "Kalau paket gue ilang gimana dong?",
    "Kalau barang rusak pas nyampe, bisa minta ganti nggak?",
    "Ongkir ke rumah gue kira-kira berapa?",
    "Ada gratis ongkir nggak sih?",
    // 🔹 Alternatif dalam Bahasa Inggris (Natural)
    "When exactly will my order be shipped?",
    "How many days does delivery usually take?",
    "Where can I check my tracking number?",
    "Is it possible to choose the courier myself?",
    "Do you guys deliver overseas?",
    "Why does it say delivered when I haven’t received anything?",
    "What should I do if my package gets lost?",
    "Am I eligible for a refund if the item arrives broken?",
    "Who covers the loss if the package is missing?",
    "Is shipping calculated by weight or by size?",
    // 🔹 Alternatif Percakapan / Slang Lebih Natural
    "Bro, paket gue kok belum sampe-sampe?",
    "Eh, biasanya kalau kirim barang tuh lama nggak sih?",
    "Resinya bisa dicek di mana nih?",
    "Bisa nggak sih request kurir tertentu?",
    "Ngirim ke luar kota tuh ribet nggak?",
    "Paket gue katanya udah nyampe, tapi gue belum nerima apa-apa.",
    "Kalau kurir ilangin paket gue gimana dong?",
    "Barangnya sampe-sampe udah peyok, bisa komplain nggak?",
    "Ongkir mahal banget sih, ada opsi yang lebih murah nggak?",
    "Bisa nggak minta dikirim lebih cepet?",
  ];
  const randomIndex2 = Math.floor(Math.random() * ask2.length);
  return ask2[randomIndex2];
}

function randomAsk3() {
  const ask3 = [
    "Selamat pagi, apa kabar hari ini?",
    "Selamat siang, semoga harimu menyenangkan.",
    "Selamat sore, bagaimana kabarnya?",
    "Selamat malam, semoga harimu berjalan baik.",
    "Halo, senang bisa menyapa kamu.",
    "Halo, semoga harimu lancar.",
    "Halo, bagaimana harimu sejauh ini?",
    "Halo, terima kasih sudah menyapa.",
    "Halo, semoga hari ini penuh energi.",
    "Halo, semoga harimu indah.",
    "Hai! Apa kabar?",
    "Hai, bagaimana kabar hari ini?",
    "Hai, semoga kamu baik-baik saja.",
    "Hai, senang ketemu lagi.",
    "Hai, ada cerita seru hari ini?",
    "Hai, bagaimana mood kamu?",
    "Hai, semoga harinya menyenangkan.",
    "Hai, apa yang lagi kamu lakukan?",
    "Hai, kabar baik kan?",
    "Hai, selamat datang!",
    "Good morning, how are you today?",
    "Good afternoon, hope your day is going well.",
    "Good evening, how have you been?",
    "Hello, thank you for joining.",
    "Hi there, welcome!",
    "Hello, how’s your day?",
    "Good day, how are things going?",
    "Hello, nice to meet you.",
    "Hi, hope everything’s good.",
    "Hello, wishing you a pleasant day.",
    "Hi! How’s it going?",
    "Hello! How are you doing?",
    "Hey, how’s your day so far?",
    "Hi, hope you’re doing well.",
    "Hello, good to see you here.",
    "Hey there! How’s life treating you?",
    "Hi, how’s your morning been?",
    "Hello, how’s your afternoon?",
    "Hi, glad you’re here!",
    "Hey, how’s everything going?",
    "Hey 👋, what’s up?",
    "Hiya! How’s your day?",
    "Hey, good to see you!",
    "Yo! How’s it going?",
    "Hey, what’s new?",
    "Hi! How’s your vibe today?",
    "Hey there, long time no see!",
    "Hiya, what’s happening?",
    "Hey, how are things?",
    "Hi, hope you’re having a good one!",
    "Hai 👋, gimana kabarnya?",
    "Halo, lagi sibuk atau santai?",
    "Hai, apa kabar dunia hari ini?",
    "Halo, semoga mood-mu oke.",
    "Hai, sudah makan belum?",
    "Halo, gimana kabar pagi ini?",
    "Hai, lagi ngapain sekarang?",
    "Halo, ada cerita seru?",
    "Hai, semoga harinya cerah.",
    "Halo, gimana cuaca di sana?",
    "Hi, how’s your week so far?",
    "Hey, hope you’re doing great!",
    "Hi, anything exciting today?",
    "Hi there, good vibes only!",
    "Hey, how’s your mood?",
    "Hi, glad you’re here.",
    "Hi, hope today is kind to you.",
    "Hey, wishing you a great day ahead!",
    "Hi, how are you feeling?",
    "Hey, good energy today?",
    "Hi, hope you’re smiling.",
    "Hey, sending positive vibes your way.",
    "Hey hey! How’s life?",
    "Hiya, feeling good?",
    "Hey, what’s your highlight today?",
    "Hi, hope you had your coffee ☕",
    "Hey, got any fun plans?",
    "Hi, hope today brings you joy.",
    "Hey, enjoying your day so far?",
    "Hi, hope all is well.",
    "Hey, what’s going on?",
    "Hi, wishing you peace today.",
    "Hey, what’s the vibe today?",
    "Hi, hope your day is smooth.",
    "Hey, glad to see you online.",
    "Hi, wishing you good energy.",
    "Hey, all good with you?",
    "Hi, happy to chat with you.",
    "Hey, what’s been keeping you busy?",
    "Hi, I hope your day is bright.",
    "Hey, good to connect today.",
    "Hi, what’s your plan today?",
    "Hey, how’s the morning going?",
    "Hi, hope the afternoon’s good.",
    "Hey, how’s your evening?",
    "Hi, it’s nice to see you here.",
    "Hey, how’s everything this week?",
  ];
  const randomIndex3 = Math.floor(Math.random() * ask3.length);
  return ask3[randomIndex3];
}
function randomAsk4() {
  const ask4 = [
    "Selamat datang kembali!",
    "Halo, senang bisa ngobrol lagi.",
    "Hai, apa kabar hari ini?",
    "Halo, lama tak berjumpa.",
    "Hai, semoga kamu sehat selalu.",
    "Halo, bagaimana minggu ini?",
    "Hai, ada cerita baru?",
    "Halo, apa kabar keluarga?",
    "Hai, semoga semua baik-baik aja.",
    "Halo, sudah istirahatkah?",
    "Good morning! Hope you slept well.",
    "Good afternoon! How’s your day?",
    "Good evening! How’s it going?",
    "Hello there, nice to see you.",
    "Hi, thanks for dropping by.",
    "Hello, how’s your world today?",
    "Hi, what’s happening?",
    "Hello, how have you been lately?",
    "Hi, glad you reached out.",
    "Hello, what’s new with you?",
    "Hey there 👋, good morning!",
    "Hiya, good afternoon!",
    "Hey, good evening!",
    "Hi, how’s the week treating you?",
    "Hey, long time no chat!",
    "Hi, hope your week is smooth.",
    "Hey, what’s up with your day?",
    "Hi, how’s your energy today?",
    "Hey, how’s your weekend?",
    "Hi, hope your Monday’s okay.",
    "Hey, happy Friday!",
    "Hi, wishing you a restful day.",
    "Hey, ready for a great day?",
    "Hi, how’s the start of your week?",
    "Hey, how’s your Sunday?",
    "Hi, hope today’s full of joy.",
    "Hey, wishing you good vibes.",
    "Hi, what’s keeping you busy?",
    "Hey, how’s work/life balance?",
    "Hi, hope you’re relaxed.",
    "Hey, how’s your downtime?",
    "Hi, what’s your highlight?",
    "Hey, hope you’re energized.",
    "Hi, what’s your focus today?",
    "Hey, how’s your family?",
    "Hi, hope you’re surrounded by positivity.",
    "Hey, how’s your circle?",
    "Hi, nice seeing you again.",
    "Hey, how’s your journey lately?",
    "Hai, semoga harimu indah.",
    "Halo, sudah sarapan?",
    "Hai, gimana aktivitasmu?",
    "Halo, semoga semuanya lancar.",
    "Hai, kabar baik ya?",
    "Halo, ada kabar gembira?",
    "Hai, bagaimana hari ini berjalan?",
    "Halo, senang sekali ngobrol lagi.",
    "Hai, semoga hatimu tenang.",
    "Halo, apa rencana hari ini?",
    "Hai, semoga pagimu cerah.",
    "Halo, gimana siangmu?",
    "Hai, semoga soremu santai.",
    "Halo, semoga malamnya menyenangkan.",
    "Hai, ada kejadian menarik?",
    "Halo, apa yang bikin bahagia?",
    "Hai, semoga penuh energi positif.",
    "Halo, hari ini gimana?",
    "Hai, apa yang baru?",
    "Halo, ada kabar baik?",
    "Hai, semoga sehat selalu.",
    "Halo, lagi apa sekarang?",
    "Hai, gimana cuaca di sana?",
    "Halo, semoga hari cerah.",
    "Hai, apa rencanamu minggu ini?",
    "Halo, semoga harimu damai.",
    "Hai, apa kabar teman?",
    "Halo, senang melihatmu.",
    "Hai, bagaimana semangatmu?",
    "Halo, apa kabar suasana hati?",
    "Hai, semoga tenang ya.",
    "Halo, ada hal menarik?",
    "Hai, semoga bahagia selalu.",
    "Halo, semoga banyak senyum hari ini.",
    "Hai, gimana harinya sejauh ini?",
    "Halo, kabar baik kan?",
    "Hai, semoga selalu beruntung.",
    "Halo, semoga sehat dan semangat.",
    "Hai, ada cerita lucu?",
    "Halo, gimana kabar pagi ini?",
    "Hai, apa rencana akhir pekan?",
    "Halo, semoga sore ini damai.",
    "Hai, semoga malammu menyenangkan.",
    "Halo, senang sekali bisa menyapa.",
    "Hai, semoga harinya lancar.",
    "Halo, ada kabar spesial?",
    "Hai, semoga penuh inspirasi.",
    "Halo, senang berbicara lagi.",
    "Hai, apa kabar dunia?",
    "Halo, semoga ceria selalu.",
    "Hai, gimana kabarmu?",
  ];
  const randomIndex4 = Math.floor(Math.random() * ask4.length);
  return ask4[randomIndex4];
}
function randomAsk5() {
  const ask5 = [
    "Good morning, ready for the day?",
    "Good afternoon, how’s your vibe?",
    "Good evening, how’s your mood?",
    "Hello there, hope you’re good.",
    "Hiya! How’s life?",
    "Hey, nice to connect.",
    "Hi, how are things lately?",
    "Hey there, what’s happening?",
    "Hi, hope all is well.",
    "Hey, glad to chat with you.",
    "Hi, hope today is peaceful.",
    "Hey, what’s your plan?",
    "Hi, how’s your week shaping up?",
    "Hey, what’s keeping you busy?",
    "Hi, nice to see you again.",
    "Hey, how’s everything around you?",
    "Hi, hope it’s a good day.",
    "Hey, what’s new with life?",
    "Hi, hope you’re smiling today.",
    "Hey, how’s your mood so far?",
    // Indo casual
    "Hai, semoga hari ini menyenangkan.",
    "Halo, gimana kabar teman?",
    "Hai, ada cerita hari ini?",
    "Halo, semoga senang selalu.",
    "Hai, bagaimana pagi ini?",
    "Halo, semoga penuh energi.",
    "Hai, kabar cerah?",
    "Halo, bagaimana siang ini?",
    "Hai, semoga malamnya indah.",
    "Halo, apa kabar senin?",
    "Hai, semoga minggu ini baik.",
    "Halo, gimana rencananya?",
    "Hai, semoga sukses selalu.",
    "Halo, bagaimana kabar hati?",
    "Hai, apa yang bikin bahagia?",
    "Halo, semoga banyak senyum.",
    "Hai, semoga damai selalu.",
    "Halo, gimana aktivitasmu?",
    "Hai, semoga lancar hari ini.",
    "Halo, kabar baik ya?",
    "Hi, hope your day’s amazing.",
    "Hey, what’s your highlight?",
    "Hi, good vibes only!",
    "Hey, how’s the week?",
    "Hi, hope you’re energized.",
    "Hey, what’s your favorite moment today?",
    "Hi, wishing you positivity.",
    "Hey, nice day isn’t it?",
    "Hi, how’s everything going?",
    "Hey, good to see you here.",
    "Hi, let’s make today awesome.",
    "Hey, how’s the start of the week?",
    "Hi, hope your weekend’s fun.",
    "Hey, enjoying your morning?",
    "Hi, how’s your afternoon vibe?",
    "Hey, good evening to you.",
    "Hi, hope you’re surrounded by joy.",
    "Hey, hope you’re relaxed.",
    "Hi, wishing you a good week.",
    "Hey, hope today flows smoothly.",
    "Hi, hope you’re happy right now.",
    "Hey, wishing you smiles.",
    "Hi, how’s the journey of today?",
    "Hey, good start so far?",
    "Hi, how’s everything around?",
    "Hey, hope you’re chill.",
    "Hi, sending good energy.",
    "Hey, how’s your heart today?",
    "Hi, wishing you calmness.",
    "Hey, how’s your world today?",
    "Hi, hope today’s light for you.",
    "Hey, what’s on your mind?",
    "Hi, wishing you brightness.",
    "Hey, hope you’re well rested.",
    "Hi, hope your day’s smooth.",
    "Hey, ready for a new day?",
    "Hi, glad you’re online.",
    "Hey, how’s the vibe today?",
    "Hi, hope you’re having fun.",
    "Hey, how’s your timeline?",
    "Hi, wishing you balance.",
    "Hey, hope you’re positive.",
    "Hi, what’s up this evening?",
    "Hey, how’s your energy?",
    "Hi, what’s going well?",
    "Hey, how’s your smile today?",
    "Hi, wishing you sunshine.",
    "Hey, hope your day shines.",
    "Hi, hope today feels fresh.",
    "Hey, what’s new today?",
    "Hi, good mood today?",
    "Hey, feeling cheerful?",
    "Hi, hope you’re comfy.",
    "Hey, wishing you clarity.",
    "Hi, how’s your pace today?",
    "Hey, happy to chat.",
    "Hi, hope the day’s smooth.",
    "Hey, what’s making you smile?",
    "Hi, wishing you joy today.",
    "Hey, how’s your focus?",
    "Hi, good luck with today.",
    "Hey, how’s your journey?",
    "Hi, wishing you peace.",
    "Hey, how’s your morning vibe?",
    "Hi, wishing you strength.",
    "Hey, how’s the mood right now?",
    "Hi, hope the day’s bright.",
    "Hey, what’s up with life?",
    "Hi, glad to catch you here.",
    "Hey, what’s your happy thought?",
    "Hi, wishing you calm vibes.",
    "Hey, how’s the week’s start?",
  ];
  const randomIndex5 = Math.floor(Math.random() * ask5.length);
  return ask5[randomIndex5];
}
function randomAsk6() {
  const ask6 = [
    "Selamat pagi, semoga cerah.",
    "Selamat siang, apa kabar?",
    "Selamat sore, semoga tenang.",
    "Selamat malam, semoga damai.",
    "Halo, kabar baik ya?",
    "Hai, senang ngobrol lagi.",
    "Halo, semoga bahagia.",
    "Hai, semoga sehat selalu.",
    "Halo, semoga penuh inspirasi.",
    "Hai, semoga penuh energi.",
    "Good morning, sunshine!",
    "Good afternoon, how’s it going?",
    "Good evening, hope you’re well.",
    "Hello, welcome back!",
    "Hi, good to see you.",
    "Hello, how’s your spirit?",
    "Hi there, let’s chat!",
    "Hello, what’s happening today?",
    "Hi, wishing you well.",
    "Hello, how’s your smile?",
    "Hey, new day new vibe!",
    "Hiya, happy to see you.",
    "Hey, how’s your world?",
    "Hi, what’s the good news?",
    "Hey, how’s your weekend plan?",
    "Hi, hope you’re enjoying today.",
    "Hey, how’s your mood swing?",
    "Hi, hope you’re relaxed today.",
    "Hey, good times ahead?",
    "Hi, hope today is smooth sailing.",
    "Hey, happy midweek!",
    "Hi, hope your energy is up.",
    "Hey, what’s today’s vibe?",
    "Hi, wishing you happiness.",
    "Hey, hope you’re smiling wide.",
    "Hi, what’s exciting today?",
    "Hey, enjoying the day?",
    "Hi, hope you’re content.",
    "Hey, nice seeing you.",
    "Hi, what’s your highlight today?",
    "Hey, hope you’re peaceful.",
    "Hi, wishing you positive energy.",
    "Hey, what’s on your plate today?",
    "Hi, hope your day is balanced.",
    "Hey, how’s your flow?",
    "Hi, what’s sparking joy?",
    "Hey, hope you’re good.",
    "Hi, glad you’re around.",
    "Hey, how’s your sunshine?",
    "Hi, what’s brightening your day?",
    "Hey, happy to greet you.",
    "Hi, how’s your spirit today?",
    "Hey, wishing you wellness.",
    "Hi, good mood so far?",
    "Hey, what’s been fun?",
    "Hi, glad to connect again.",
    "Hey, how’s your today?",
    "Hi, wishing you ease.",
    "Hey, what’s up friend?",
    "Hi, wishing you light.",
    "Hey, how’s your day vibe?",
    "Hi, good afternoon vibes?",
    "Hey, good morning energy?",
    "Hi, hope the evening’s calm.",
    "Hey, wishing you smiles today.",
    "Hi, hope the day feels good.",
    "Hey, what’s new with you?",
    "Hi, glad to say hello.",
    "Hey, how’s your week vibe?",
    "Hi, hope today is kind.",
    "Hey, wishing you cheer.",
    "Hi, what’s inspiring today?",
    "Hey, glad we’re chatting.",
    "Hi, what’s your mood?",
    "Hey, good luck today.",
    "Hi, wishing you a sunny day.",
    "Hey, how’s your joy today?",
    "Hi, peace and light to you.",
    "Hey, what’s good this week?",
    "Hi, wishing you balance today.",
    "Hey, what’s making you smile?",
    "Hi, cheers to today.",
    "Hey, how’s your comfort today?",
    "Hi, hope today’s positive.",
    "Hey, what’s keeping you cheerful?",
    "Hi, nice catching up.",
    "Hey, how’s your morning vibe?",
    "Hi, hope you’re happy today.",
    "Hey, glad to greet you.",
    "Hi, wishing you luck.",
    "Hey, what’s new in life?",
    "Hi, hoping today is smooth.",
    "Hey, glad to meet again.",
    "Hi, have a joyful day.",
    "Hey, how’s your smile?",
    "Hi, wishing you warmth.",
    "Hey, hope today is bright.",
    "Hi, have a great day!",
    "Hey, let’s start fresh.",
  ];
  const randomIndex6 = Math.floor(Math.random() * ask6.length);
  return ask6[randomIndex6];
}

function randomAnswer() {
  const answer = [
    "Biasanya barang dikirim 1x24 jam setelah pesanan dikonfirmasi.",
    "Waktu pengiriman tergantung lokasi, tapi biasanya 2–5 hari kerja.",
    "Kamu bisa cek status kiriman pakai nomor resi yang kami kasih.",
    "Bisa banget! Tinggal pilih ekspedisi yang tersedia pas checkout.",
    "Iya, kami bisa kirim ke luar kota dan luar negeri juga kok.",
    "Kalau status udah terkirim tapi barang belum nyampe, coba cek ke tetangga atau hubungi kurir ya.",
    "Kalau barang hilang, tenang aja, kami bantu proses klaim ke ekspedisi.",
    "Coba hubungi kami dulu ya, nanti tim kami bantu cekin.",
    "Kalau rusak karena pengiriman, kami bantu proses penggantian atau refund kok.",
    "Yang tanggung jawab biasanya ekspedisinya, tapi kami bantu prosesnya ya.",
    "Ongkir tergantung lokasi pengiriman dan berat barang, bisa dicek pas mau bayar.",
    "Iya, ongkir dihitung dari berat atau ukuran paket, tergantung ekspedisinya.",
    "Kadang ada promo free ongkir, pantengin terus infonya ya!",
    "Iya bisa, asal ekspedisinya support COD. Nanti pilih aja pas checkout.",
    "Kalau kirim ulang karena kesalahan alamat, biasanya ada tambahan ongkir ya.",
    "Kamu bisa cek status kiriman langsung lewat link tracking yang kami kirim.",
    "Setelah dikirim, kamu bakal dapet nomor resi via email atau WhatsApp.",
    "Kalau salah alamat, langsung hubungi kami biar bisa dibantu ubah sebelum dikirim.",
    "Kalau udah dikirim, perubahan alamat susah sih, tapi bisa dicoba kontak ekspedisinya.",
    "Yup, kirim ulang biasanya kena ongkir baru, tapi nanti kami info detailnya.",
    "Untuk klaim, tinggal kirim foto barang & nomor resi ke CS kami ya.",
    "Pengiriman tetap jalan Senin sampai Sabtu, Minggu dan libur biasanya off.",
    "Bisa banget request waktu, tapi tergantung kurir ya, nggak semua bisa.",
    "Kalau kamu nggak di rumah, biasanya kurir bakal coba kirim ulang besoknya.",
    "Bisa, nanti kamu ambil di kantor ekspedisi terdekat.",
    "Ongkir bisa dibayar pakai transfer, e-wallet, atau COD kalau tersedia.",
    "Bisa banget, pilih opsi pengiriman ekspres pas checkout aja.",
    "Yes! Kalau di kota tertentu, kami ada layanan same-day delivery.",
    "Ada beberapa barang yang dilarang dikirim, kayak cairan, baterai besar, atau barang berbahaya.",
    "Kalau barang yang dateng beda atau salah, langsung hubungi kami ya biar ditukar.",
    "Fix!",
    "Kadang gue mikir, hidup gue kapan bisa se aesthetic itu ya?",
    "Baru mau foto kopi aja, tangan gue udah gemeter",
    "Santai beb, yang penting hidup lo real, bukan settingan.",
    "settingan lo",
    "Lagian juga, kopi tetep enak walau gak di-post.",
    "Yoi juga sih.",
    "Tapi kalo ada konten sekalian nyari cuan dong, siapa tau bisa jadi selebgram juga kan?",
    "Aminin dulu beb",
    "sayang",
    "beb",
    "siapa tau abis ini ada brand endorse lo",
    "mie mulu",
    "keriting usus",
  ];
  const randomIndex = Math.floor(Math.random() * answer.length);
  return answer[randomIndex];
}

export {
  randomAnswer,
  randomAsk,
  randomAsk2,
  randomAsk3,
  randomAsk4,
  randomAsk5,
  randomAsk6,
  generateRandomQuote,
};
