const userData = [
    { name: 'John Doe', whatsapp: '081234567890', division: 'Sales' },
    { name: 'Jane Smith', whatsapp: '081298765432', division: 'Support' },
    { name: 'Mark Taylor', whatsapp: '081212345678', division: 'Development' }
  ];

// export default userData;

const userDivisi = [
    // {division: 'HUB AEG'},
    // {division: 'HUB AGR'},
    // {division: 'HUB AMQ'},
    // {division: 'HUB ARD'},
  //   {division: 'HUB ATB'},
  //   {division: 'HUB ATC'},
  //   {division: 'HUB BBR'},
  //   {division: 'HUB BDB'},
  //   {division: 'HUB BDJ'}, 
  //   {division: 'HUB BDO'},
  //   {division: 'HUB BDS'},
  //   {division: 'HUB BDU'},
  //   {division: 'HUB BDW'},
  //   {division: 'HUB BEJ'},
  //   {division: 'HUB BGK'},
  //   {division: 'HUB BIB'},
  //   {division: 'HUB BIK'},
  //   {division: 'HUB BIT'},
  //   {division: 'HUB BJB'},
  //   {division: 'HUB BJI'},
  //   {division: 'HUB BJN'},
  //   {division: 'HUB BJO'},
  //   {division: 'HUB BKI'},
  //   {division: 'HUB BKL'},
  //   {division: 'HUB BKN'},
  //   {division: 'HUB BKO'},
  //   {division: 'HUB BKS'},
  //   {division: 'HUB BKT'},
  //   {division: 'HUB BLG'},
  //   {division: 'HUB BLI'},
  //   {division: 'HUB BLS'},
  //   {division: 'HUB BMU'},
  //   {division: 'HUB BNO'},
  //   {division: 'HUB BOB'},
  //   {division: 'HUB BOO'},
  //   {division: 'HUB BPN'},
  //   {division: 'HUB BRB'},
  //   {division: 'HUB BRI'},
  //   {division: 'HUB BRJ'},
  //   {division: 'HUB BSW'},
  //   {division: 'HUB BTG'},
  //   {division: 'HUB BTH'},
  //   {division: 'HUB BTJ'},
  //   {division: 'HUB BTU'},
  //   {division: 'HUB BTW'},
  //   {division: 'HUB BUW'},
  //   {division: 'HUB BWX'},
  //   {division: 'HUB BXB'},
  //   {division: 'UB BYI'},
  //   {division: 'HUB CBI'},
  //   {division: 'HUB CBN'},
  //   {division: 'HUB CIM'},
  //   {division: 'HUB CJR'},
  //   {division: 'HUB CJT'},
  //   {division: 'HUB CKP'},
  //   {division: 'HUB CKR'},
  //   {division: 'HUB CLN'},
  //   {division: 'HUB CMS'},
  //   {division: 'HUB CRP'},
  //   {division: 'HUB CXP'},
  //   {division: 'HUB DJB'},
  //   {division: 'HUB DJJ'},
  //   {division: 'HUB DMK'},
  //   {division: 'HUB DPK'},
  //   {division: 'HUB DPS'},
  //   {division: 'HUB DPU'},
  //   {division: 'HUB DRI'},
  //   {division: 'HUB DRY'},
  //   {division: 'HUB DUM'},
  //   {division: 'HUB DVE'},
  //   {division: 'HUB ENE'},
  //   {division: 'HUB FFQ'},
  //   {division: 'HUB GIN'},
  //  {division: ' HUB GNS'},
  //   {division: 'HUB GNT'},
  //   {division: 'HUB GRS'},
  //   {division: 'HUB GRT'},
  //   {division: 'HUB GST'},
  //   {division: 'HUB GTO'},
  //   {division: 'HUB GTX'},
  //   {division: 'HUB HLP'},
  //  {division: ' HUB IDY'},
  //   {division: 'HUB JBA'},
  //  {division: ' HUB JBB'},
  //  {division: ' HUB JBC'},
  //   {division: 'HUB JBD'},
  //   {division: 'HUB JBG'},
  //  {division: ' HUB JBR'},
  //  {division: ' HUB JKB'},
  //  {division: ' HUB JKK'},
  //   {division: 'HUB JKP'},
  //  {division: ' HUB JKS'},
  //   {division: 'HUB JKT'},
  //   {division: 'HUB JKU'},
  //   {division: 'HUB JOG'},
  //   {division: 'HUB JPA'},
  //   {division: 'HUB JPB'},
  //   {division: 'HUB JSA'},
  //   {division: 'HUB JSB'},
  //   {division: 'HUB JSC'},
  //   {division: 'HUB JSD'},
  //   {division: 'HUB JTB'},
  //  {division: ' HUB JTC'},
  //  {division: ' HUB JUA'},
  //   {division: 'HUB JUB'},
  //  {division: ' HUB KAG'},
  //   {division: 'HUB KBB'},
  //   {division: 'HUB KBJ'},
  //   {division: 'HUB KBM'},
  //   {division: 'HUB KBP'},
  //   {division: 'HUB KBS'},
  //   {division: 'HUB KBT'},
  //   {division: 'HUB KBU'},
  //   {division: 'HUB KDI'},
  //   {division: 'HUB KDL'},
  //   {division: 'HUB KDR'},
  //   {division: 'HUB KDS'},
  //   {division: 'HUB KKA'},
  //   {division: 'HUB KKP'},
  //   {division: 'HUB KLT'},
  //   {division: 'HUB KMA'},
  //   {division: 'HUB KNG'},
  //  {division: ' HUB KNO'},
  //  {division: ' HUB KOE'},
  //   {division: 'HUB KPN'},
  //   {division: 'HUB KRG'},
  //   {division: 'HUB KRW'},
  //   {division: 'HUB KSR'},
  //   {division: 'HUB KTB'},
  //   {division: 'HUB KTG'},
  //   {division: 'HUB KTP'},
  //   {division: 'HUB LBJ'},
  //   {division: 'HUB LBP'},
  //   {division: 'HUB LGS'},
  //   {division: 'HUB LHT'},
  //   {division: 'HUB LKA'},
  //   {division: 'HUB LLG'},
  //   {division: 'HUB LMJ'},
  //   {division: 'HUB LMN'},
  //   {division: 'HUB LOP'},
  //   {division: 'HUB LSW'},
  //   {division: 'HUB LTG'},
  //   {division: 'HUB LTM'},
  //  {division: 'HUB LUV'},
  //   {division: 'HUB LUW'},
  //   {division: 'HUB MDC'},
  //   {division: 'HUB MDN'},
  //   {division: 'HUB MDR'},
  //   {division: 'HUB MES'},
  //   {division: 'HUB MET'},
  //   {division: 'HUB MGL'},
  //   {division: 'HUB MJA'},
  //   {division: 'HUB MJK'},
  //   {division: 'HUB MKQ'},
  //   {division: 'HUB MKW'},
  //   {division: 'HUB MLB'},
  //   {division: 'HUB MLG'},
  //   {division: 'HUB MMJ'},
  //   {division: 'HUB MOF'},
  //   {division: 'HUB MRD'},
  //   {division: 'HUB MSH'},
  //   {division: 'HUB MTW'},
  //   {division: 'HUB MUE'},
  //   {division: 'HUB NBX'},
  //   {division: 'HUB NTX'},
  //   {division: 'HUB PBM'},
  //   {division: 'HUB PBO'},
  //   {division: 'HUB PCI'},
  //   {division: 'HUB PDG'},
  //   {division: 'HUB PDL'},
  //   {division: 'HUB PDN'},
  //   {division: 'HUB PGI'},
  //   {division: 'HUB PGK'},
  //   {division: 'HUB PKL'},
  //   {division: 'HUB PKN'},
  //   {division: 'HUB PKR'},
  //   {division: 'HUB PKU'},
  //   {division: 'HUB PKY'},
  //   {division: 'HUB PLI'},
  //   {division: 'HUB PLM'},
  //   {division: 'HUB PLP'},
  //   {division: 'HUB PLW'},
  //   {division: 'HUB PMK'},
  //   {division: 'HUB PML'},
  //   {division: 'HUB PMS'},
  //   {division: 'HUB PNK'},
  //   {division: 'HUB PNN'},
  //   {division: 'HUB PON'},
  //   {division: 'HUB PPN'},
  //   {division: 'HUB PPU'},
  //   {division: 'HUB PRE'},
  //   {division: 'HUB PRM'},
  //   {division: 'HUB PRR'},
  //   {division: 'HUB PRT'},
  //   {division: 'HUB PRW'},
  //   {division: 'HUB PSJ'},
  //   {division: 'HUB PSN'},
  //   {division: 'HUB PSP'},
  //   {division: 'HUB PTI'},
  //   {division: 'HUB PTS'},
  //   {division: 'HUB PWD'},
  //   {division: 'HUB PWK'},
  //   {division: 'HUB PWO'},
  //   {division: 'HUB PYK'},
  //   {division: 'HUB RAP'},
  //   {division: 'HUB RGT'},
  //   {division: 'HUB RHA'},
  //   {division: 'HUB RMB'},
    {division: 'HUB RTI'},
    // {division: 'HUB SBB'},
    {division: 'HUB SBG'},
    {division: 'HUB SBP'},
    {division: 'HUB SBS'},
    {division: 'HUB SDW'},
    {division: 'HUB SER'},
    {division: 'HUB SGR'},
    {division: 'HUB SGU'},
    {division: 'HUB SIT'},
    {division: 'HUB SJB'},
    {division: 'HUB SJO'},
    {division: 'HUB SJP'},
    {division: 'HUB SJS'},
    {division: 'HUB SJT'},
    {division: 'HUB SJU'},
    {division: 'HUB SKD'},
    {division: 'HUB SKW'},
    {division: 'HUB SKY'},
    {division: 'HUB SLG'},
    {division: 'HUB SLI'},
    {division: 'HUB SLK'},
    {division: 'HUB SMD'},
    {division: 'HUB SMI'},
    {division: 'HUB SMP'},
    {division: 'HUB SMQ'},
    {division: 'HUB SOC'},
    {division: 'HUB SOF'},
    {division: 'HUB SOQ'},
    {division: 'HUB SPG'},
    {division: 'HUB SPN'},
    {division: 'HUB SPP'},
    {division: 'HUB SRA'},
    {division: 'HUB SRG'},
    {division: 'HUB SRI'},
    {division: 'HUB SRJ'},
    {division: 'HUB SST'},
    {division: 'HUB STG'},
    {division: 'HUB SUB'},
    {division: 'HUB SUU'},
    {division: 'HUB SWQ'},
    {division: 'HUB TBK'},
    {division: 'HUB TBN'},
    {division: 'HUB TBW'},
    {division: 'HUB TGB'},
    {division: 'HUB TGL'},
    {division: 'HUB TGR'},
    {division: 'HUB TGS'},
    {division: 'HUB TIM'},
    {division: 'HUB TJQ'},
    {division: 'HUB TJS'},
    {division: 'HUB TKG'},
    {division: 'HUB TKN'},
    {division: 'HUB TLG'},
    {division: 'HUB TLI'},
    {division: 'HUB TLW'},
    {division: 'HUB TMH'},
    {division: 'HUB TNB'},
    {division: 'HUB TNJ'},
    {division: 'HUB TOB'},
    {division: 'HUB TPB'},
    {division: 'HUB TPE'},
    {division: 'HUB TPK'},
    {division: 'HUB TPR'},
    {division: 'HUB TRG'},
    {division: 'HUB TRK'},
    {division: 'HUB TRL'},
    {division: 'HUB TSB'},
    {division: 'HUB TSM'},
    {division: 'HUB TTE'},
    {division: 'HUB TTG'},
    {division: 'HUB TUB'},
    {division: 'HUB UNH'},
    {division: 'HUB UPG'},
    {division: 'HUB UTG'},
    {division: 'HUB WGP'},
    {division: 'HUB WMN'},
    {division: 'HUB WNB'},
    {division: 'HUB WNG'},
    {division: 'HUB WNO'},
    {division: 'HUB WTS'},
    {division: 'HUB YIA'},
];
export default userDivisi;