[
  "Aplikasi berhenti merespons saat saya menekan tombol bayar",
  "Halaman checkout tiba-tiba kosong sebelum transaksi selesai",
  "Sistem loading terlalu lama dan tidak kunjung masuk ke pembayaran",
  "Aplikasi crash saat saya memilih metode pembayaran",
  "Saya tidak bisa melanjutkan checkout karena halaman stuck",
  "Layar pembayaran membeku dan tidak bisa disentuh",
  "Aplikasi menutup sendiri saat proses transaksi",
  "Sistem error ketika saya mencoba menyelesaikan pesanan",
  "Pembayaran gagal tanpa pesan kesalahan yang jelas",
  "Aplikasi terasa sangat lambat saat jam sibuk",
  "Saya tidak bisa login meskipun data sudah benar",
  "Kode OTP tidak pernah saya terima",
  "Email verifikasi tidak masuk ke inbox",
  "Sistem logout otomatis tanpa alasan",
  "Halaman produk tidak bisa dibuka",
  "Gambar produk gagal dimuat",
  "Aplikasi terus loading tanpa hasil",
  "Notifikasi tidak muncul meskipun status berubah",
  "Error muncul saat membuka halaman promo",
  "Keranjang belanja tiba-tiba kosong sendiri",
  "Produk hilang dari wishlist tanpa saya hapus",
  "Sistem tidak menyimpan alamat pengiriman",
  "Aplikasi tidak merespons saat ganti metode bayar",
  "Halaman refund selalu error",
  "Fitur retur tidak bisa diakses",
  "Aplikasi terasa berat setelah update terbaru",
  "Saya tidak bisa mengubah jumlah produk",
  "Tombol checkout tidak bisa diklik",
  "Aplikasi freeze saat buka detail pesanan",
  "Riwayat transaksi tidak bisa ditampilkan",
  "Sistem gagal memuat status pesanan",
  "Bug muncul saat saya scroll halaman produk",
  "Aplikasi restart sendiri berulang kali",
  "Pembayaran terpotong tapi status masih pending",
  "Saya tidak bisa menghubungkan akun e-wallet",
  "Error muncul saat memasukkan kode promo",
  "Sistem menolak voucher tanpa alasan jelas",
  "Aplikasi menampilkan halaman putih kosong",
  "Proses login terlalu sering gagal",
  "Saya tidak bisa menyimpan metode pembayaran",
  "Paket saya belum sampai meski estimasi sudah lewat",
  "Pengiriman tidak bergerak sejak kemarin",
  "Status pengiriman tidak diperbarui",
  "Paket saya tertahan di gudang sortir",
  "Pesanan saya hilang dari riwayat",
  "Paket dikirim ke alamat yang salah",
  "Barang saya diterima orang lain",
  "Paket datang dalam kondisi rusak",
  "Paket tiba dalam keadaan basah",
  "Barang yang saya terima tidak lengkap",
  "Pesanan ditandai selesai padahal belum diterima",
  "Pengiriman tertunda tanpa penjelasan",
  "Kurir tidak pernah menghubungi saya",
  "Paket gagal antar tanpa konfirmasi",
  "Alamat dianggap tidak ditemukan padahal benar",
  "Paket salah rute pengiriman",
  "Pengiriman tiba-tiba berubah jadwal",
  "Paket dipending tanpa informasi",
  "Status tracking tidak bisa diakses",
  "Barang yang datang cacat",
  "Produk tidak sesuai deskripsi",
  "Pesanan dibatalkan otomatis",
  "Paket terlalu lama di pusat sortir",
  "Barang datang dalam kondisi tertekuk",
  "Pengiriman lebih lama dari estimasi",
  "Paket tidak pernah sampai ke saya",
  "Pesanan saya tidak bisa dilacak",
  "Informasi pengiriman tidak transparan",
  "Paket tertahan karena data alamat",
  "Barang yang diterima berbeda warna",
  "Dapatkan cashback tambahan untuk pembelian tertentu",
  "Promo gratis ongkir tanpa minimum belanja",
  "Diskon besar tersedia sepanjang bulan",
  "Flash sale tengah malam dengan stok terbatas",
  "Promo buy one get one spesial",
  "Voucher eksklusif untuk pengguna aktif",
  "Diskon harian dengan penawaran berbeda",
  "Cashback instan tanpa syarat",
  "Promo akhir pekan super hemat",
  "Potongan harga untuk pembelian kedua",
  "Diskon spesial pengguna setia",
  "Promo bundling lebih hemat",
  "Diskon besar kategori elektronik",
  "Voucher terbatas siap diklaim",
  "Promo pengiriman instan murah",
  "Cashback dua kali lipat hari ini",
  "Promo kejutan harian",
  "Diskon musiman semua kategori",
  "Promo kode eksklusif tambahan",
  "Potongan besar kebutuhan rumah tangga",
  "Diskon besar produk digital",
  "Promo kupon harian",
  "Cashback metode pembayaran tertentu",
  "Promo quantity discount",
  "Bonus pembelian minimal tertentu",
  "Hadiah langsung pembelian premium",
  "Promo akhir bulan terbaik",
  "Flash deal super cepat",
  "Promo ongkir seharian penuh",
  "Diskon fashion besar-besaran",
  "Saya ingin memastikan status pesanan saya",
  "Mohon bantuan untuk mengecek transaksi",
  "Saya membutuhkan informasi lebih lanjut",
  "Tolong bantu saya menyelesaikan masalah ini",
  "Saya ingin klarifikasi terkait pesanan",
  "Mohon penjelasan terkait status saya",
  "Saya ingin update terbaru",
  "Tolong cek akun saya",
  "Saya butuh bantuan segera",
  "Mohon tindak lanjut secepatnya",
  "Saya ingin solusi yang jelas",
  "Tolong bantu proses ini",
  "Saya ingin konfirmasi pembayaran",
  "Mohon dicek ulang pesanan saya",
  "Saya berharap ada kejelasan",
  "Tolong bantu perbaiki masalah ini",
  "Saya ingin memastikan tidak ada kesalahan",
  "Mohon respon secepatnya",
  "Saya ingin bantuan teknis",
  "Tolong cek sistemnya",
  "Saya butuh informasi pengiriman",
  "Mohon klarifikasi status",
  "Saya ingin bantuan customer service",
  "Tolong bantu saya memahami masalah ini",
  "Saya berharap ada solusi cepat",
  "Mohon diperiksa kembali",
  "Saya ingin kepastian",
  "Tolong cek detail transaksi",
  "Saya membutuhkan bantuan lanjutan",
  "Mohon update terbaru",
];
