name: send random quotes to all registered number in staging

on:
  push: # Run the tests on every push
    branches:
      - main
  schedule:
    # - cron: "0 0,8,10,12,14,16,18,20,22 * * *"
    # - cron: "0 0,8,16 * * *"
    - cron: "0 4,9,17,23 * * *" #broadcast
    # - cron: "30 1,9,17 * * *"  # Runs at 1:30 AM, 9:30 AM, and 5:30 PM (UTC)
    # - cron: "15 2,10,18 * * *" # Runs at 2:15 AM, 10:15 AM, and 6:15 PM (UTC)

jobs:
  cypress-run-staging:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress run - Staging
        env:
          CYPRESS_baseUrl: "https://staging.example.test"
        # run: npx cypress run --spec "cypress/e2e/1SAP-send random message2-9.cy.js"
        run: npx cypress run --spec "cypress/e2e/OPEN_API/OpenAPI_broadcast.cy.js" #run for broadcast
